import os
import time
from argparse import ArgumentParser
from pathlib import Path

from src.config.settings import get_settings
from src.crew.test_generator_crew import TestGeneratorCrewRunner
from src.utils.git_utils import get_changed_files
from src.utils.pr_utils import (
    build_pr_body,
    create_branch_and_commit,
    get_current_branch,
    get_repo_full_name,
    open_pull_request,
    add_pr_comment,
    parse_test_files_from_output,
    push_branch,
    write_test_files,
)


def parse_args():
    parser = ArgumentParser(description="Agente gerador de testes unitários baseado no relatório de QA")

    parser.add_argument(
        "--repo-path",
        default=".",
        help="Caminho do repositório alvo",
    )

    parser.add_argument(
        "--report-file",
        default="outputs/analysis.md",
        help="Caminho do relatório de QA gerado pelo primeiro agente",
    )

    parser.add_argument(
        "--base-sha",
        default=None,
        help="Commit base para identificar arquivos alterados",
    )

    parser.add_argument(
        "--head-sha",
        default=None,
        help="Commit final para identificar arquivos alterados",
    )

    parser.add_argument(
        "--branch-prefix",
        default="qagent/tests",
        help="Prefixo da branch a ser criada",
    )

    parser.add_argument(
        "--base-branch",
        default=None,
        help="Branch base para o PR (padrão: branch atual)",
    )

    parser.add_argument(
        "--no-pr",
        action="store_true",
        help="Apenas gera os testes sem criar PR",
    )

    return parser.parse_args()


def read_report(report_file: str) -> str:
    path = Path(report_file)
    if not path.exists():
        raise FileNotFoundError(f"Relatório não encontrado: {report_file}")
    return path.read_text(encoding="utf-8")


def read_file_content(repo_path: Path, file_path: str) -> str:
    path = repo_path / file_path
    if not path.exists():
        raise FileNotFoundError(f"Arquivo não encontrado: {path}")
    return path.read_text(encoding="utf-8")


def extract_report_sections(full_report: str) -> dict[str, str]:
    """Divide o relatório completo em seções por arquivo analisado."""
    sections: dict[str, str] = {}
    parts = full_report.split("# Arquivo analisado: ")

    for part in parts[1:]:
        lines = part.strip().split("\n", 1)
        if lines:
            file_path = lines[0].strip()
            content = lines[1].strip() if len(lines) > 1 else ""
            sections[file_path] = content

    return sections


def main() -> None:
    args = parse_args()
    repo_path = Path(args.repo_path).resolve()

    settings = get_settings()
    crew_runner = TestGeneratorCrewRunner(settings)

    qa_report = read_report(args.report_file)
    report_sections = extract_report_sections(qa_report)

    if not report_sections:
        print("Nenhuma seção de arquivo encontrada no relatório de QA.")
        return

    changed_files = list(report_sections.keys())

    all_test_files: dict[str, str] = {}
    analyzed_files: list[str] = []

    for file_path in changed_files:
        print(f"\n🧪 Gerando testes para: {file_path}")

        try:
            code_content = read_file_content(repo_path, file_path)
        except FileNotFoundError:
            print(f"  ⚠️ Arquivo não encontrado no repo, pulando: {file_path}")
            continue

        section_report = report_sections[file_path]

        result = crew_runner.run(
            qa_report=section_report,
            file_path=file_path,
            code_content=code_content,
            repo_path=str(repo_path),
        )

        test_files = parse_test_files_from_output(result)

        if not test_files:
            print(f"  ⚠️ Nenhum arquivo de teste extraído para: {file_path}")
            continue

        all_test_files.update(test_files)
        analyzed_files.append(file_path)

        for tf in test_files:
            print(f"  ✅ Teste gerado: {tf}")

    if not all_test_files:
        print("\n❌ Nenhum teste foi gerado.")
        return

    # Escreve os arquivos de teste no repositório
    created_files = write_test_files(repo_path, all_test_files)
    print(f"\n📁 {len(created_files)} arquivo(s) de teste criado(s)")

    if args.no_pr:
        print("\n✅ Testes gerados com sucesso (modo --no-pr, PR não criado)")
        return

    # Cria branch, commit, push e abre PR
    base_branch = args.base_branch or get_current_branch(repo_path)
    timestamp = int(time.time())
    branch_name = f"{args.branch_prefix}-{timestamp}"

    print(f"\n🌿 Criando branch: {branch_name}")
    create_branch_and_commit(
        repo_path=repo_path,
        branch_name=branch_name,
        test_files=created_files,
        commit_message=f"test: add unit tests generated by QAgent [skip-qagent]\n\nTests based on QA report for: {', '.join(analyzed_files)}",
    )

    print(f"🚀 Fazendo push para origin/{branch_name}")
    push_branch(repo_path, branch_name)

    github_token = os.getenv("GITHUB_TOKEN", "")
    if not github_token:
        print("\n⚠️ GITHUB_TOKEN não definido. Push realizado, mas PR não foi criado.")
        print(f"  Crie o PR manualmente da branch: {branch_name}")
        return

    repo_full_name = get_repo_full_name(repo_path)
    pr_body = build_pr_body(qa_report, created_files, analyzed_files)

    pr_title = f"🧪 QAgent: Testes unitários para {', '.join(analyzed_files)}"
    if len(pr_title) > 120:
        pr_title = f"🧪 QAgent: Testes unitários para {len(analyzed_files)} arquivo(s)"

    print(f"\n📝 Abrindo PR em {repo_full_name}...")
    pr_url = open_pull_request(
        github_token=github_token,
        repo_full_name=repo_full_name,
        branch_name=branch_name,
        base_branch=base_branch,
        title=pr_title,
        body=pr_body,
    )

    print(f"\n✅ PR criado com sucesso: {pr_url}")

    # Post review-request comment on the PR
    try:
        add_pr_comment(
            github_token=github_token,
            repo_full_name=repo_full_name,
            branch_name=branch_name,
            comment_body=(
                "@copilot valide os testes deste pr, sua estrutura e aderência ao projeto."
            ),
        )
        print("💬 Comentário de validação postado no PR.")
    except Exception as exc:
        print(f"⚠️ Não foi possível postar comentário no PR: {exc}")


if __name__ == "__main__":
    main()
